# Radical Panic is free software, MIT, with no ads and no tracking.
# It runs on donations. Uncomment and fill in whichever of these you use —
# GitHub renders a "Sponsor" button on the repository from this file.

# github: [RaushanSakhibzadin]
# ko_fi: your-ko-fi-name
# buy_me_a_coffee: your-bmac-name
# liberapay: your-liberapay-name
# open_collective: your-collective-name
# custom: ["https://example.com/donate"]
